# Generated by Django 3.1.4 on 2021-01-02 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_event_sourcing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHandlerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], db_index=True, default='processing', max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handler_logs', to='django_event_sourcing.event')),
            ],
        ),
    ]
