# Generated by Django 3.1.4 on 2021-01-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_event_sourcing", "0003_rename_event_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="context",
            field=models.JSONField(db_index=True, default=dict),
        ),
    ]
