# Generated by Django 3.1.4 on 2021-01-13 13:57

from django.db import migrations, models
import django_event_sourcing.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_event_sourcing", "0004_event_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="context",
            field=models.JSONField(
                db_index=True,
                default=dict,
                encoder=django_event_sourcing.models.ModelJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(
                encoder=django_event_sourcing.models.ModelJSONEncoder
            ),
        ),
    ]
