# Generated by Django 3.1.4 on 2021-01-13 13:48

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_event_sourcing", "0004_event_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="context",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
