# Generated by Django 3.1.4 on 2021-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_event_sourcing", "0005_eventdataencoder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsideeffectlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                    ("skipped", "Skipped"),
                ],
                db_index=True,
                default="processing",
                max_length=12,
            ),
        ),
    ]
